import { tool } from "@ericsanchezok/synergy-plugin/tool";
import fs from "fs/promises";
import z from "zod";
import { ResearchFS } from "../fs";
import { getMutex, LockTimeoutError, withLockTimeout } from "../lock";
import { log } from "../log";
import { updateActivePhaseRun } from "../phase-run";
import type { Edge, GapYaml, LitPaperYaml, StateYaml, WikiLogEntry } from "../schema";
import { EdgeType, GapStatus, PaperRelevance } from "../schema";
import { ResearchTimeline } from "../timeline";
import { ENTITY_DIRS, mdMeta, notInitialized, withGuard } from "./shared";

const wikiMutex = getMutex("wiki");

async function entityExists(id: string): Promise<boolean> {
  // Gap IDs: validate they actually exist in gap_map.yaml
  if (/^G\d+$/.test(id)) {
    try {
      const gapMap = await ResearchFS.readYaml<{ gaps: Array<{ id: string }> }>(
        ResearchFS.resolve("literature/gap_map.yaml"),
      );
      return gapMap?.gaps?.some((g) => g.id === id) ?? false;
    } catch {
      return false;
    }
  }

  // Literature papers: check literature/papers/{slug}.yaml
  const litPaperPath = ResearchFS.resolve("literature/papers", `${id}.yaml`);
  if (await ResearchFS.exists(litPaperPath)) return true;

  const auxiliaryDirs: Array<{ prefix: string; dir: string }> = [
    { prefix: "rqg_", dir: "rqg" },
    { prefix: "diag_", dir: "diagnoses" },
    { prefix: "code_artifact_", dir: "code_artifacts" },
    { prefix: "artifact_", dir: "code_artifacts" },
  ];
  for (const { prefix, dir } of auxiliaryDirs) {
    if (id.startsWith(prefix)) {
      return ResearchFS.exists(ResearchFS.resolve(dir, `${id}.yaml`));
    }
  }

  // Research entities with known prefixes (idea_001 → ideas/idea_001.yaml)
  const underscoreIdx = id.indexOf("_");
  if (underscoreIdx > 0) {
    const prefix = id.slice(0, underscoreIdx);
    const dir = ENTITY_DIRS[prefix];
    if (dir) {
      const filePath = ResearchFS.resolve(dir, `${id}.yaml`);
      return ResearchFS.exists(filePath);
    }
  }

  // Unknown prefix — block edge creation to prevent dangling references
  log.warn("Wiki", `entityExists: unknown prefix in "${id}" — blocking edge creation`);
  return false;
}

const DESCRIPTION = `Topic-level shared knowledge base for the entire research project — papers, gaps, and relationships.

This is the single source of truth for literature data in .research/literature/.
NOT the manuscript tool (that's research_paper). This manages the knowledge graph that informs the manuscript.

Data managed:
- Papers: papers/{slug}.yaml + .md + bib entry
- Relationships: edges.jsonl (typed edges between papers, ideas, experiments, gaps)
- Gaps: gap_map.yaml (open research questions)
- Compressed view: LIT_CONTEXT.md (generated by query)
- Mutation log: log.jsonl

Actions:
- ingest_paper: Register a new paper. Creates yaml, md template, and bib entry. Auto-deduplicates by slug.
  When arxiv is provided, automatically fetches metadata: DBLP → Semantic Scholar → arXiv API.
  DBLP is the gold standard for CS papers (complete venue/pages/editors BibTeX).
  For non-arXiv journal DOIs, uses CrossRef.
  Fallback to manual params if all APIs unavailable.
- link: Add a typed relationship edge (extends, contradicts, inspired_by, supports, invalidates, etc.).
- register_gap: Register a research gap. Auto-assigns gap ID (G01, G02, ...).
- update_entry: Update paper fields (relevance, tags) or gap fields (status, linked_ideas).
- query: Generate/update LIT_CONTEXT.md — a compressed view for downstream agents.
- lint: Health check (orphan papers, stale gaps, dangling edges, sparse pages, duplicate bib entries).
- verify_bib: Verify all BibTeX entries in references.bib against authoritative sources (DBLP → S2 → arXiv).
  Reports VERIFIED / MISMATCH / UNVERIFIABLE per entry. Use during paper-audit for citation accuracy.
- stats: Quick statistics overview.

Files: .research/literature/ (papers/*.yaml + *.md, gap_map.yaml, edges.jsonl, references.bib, LIT_CONTEXT.md)
IMPORTANT: Use this tool to manage papers — do NOT use write/note_write for literature data.`;

function slugify(title: string, firstAuthor?: string, year?: number): string {
  const keyword = title
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, "")
    .split(/\s+/)
    .filter(
      (w) =>
        w.length > 3 &&
        !["that", "this", "with", "from", "using", "based", "which", "their", "where", "when"].includes(w),
    )
    .slice(0, 3)
    .join("_");

  const author = firstAuthor ? (firstAuthor.split(",").at(0)?.trim().toLowerCase().replace(/\s+/g, "") ?? "") : "";
  const y = year?.toString() ?? "";

  const parts = [author, y, keyword].filter(Boolean);
  return parts.join("_") || "untitled";
}

function bibEntry(
  slug: string,
  title: string,
  authors: string[],
  year: number | undefined,
  venue: string | undefined,
  arxiv: string | undefined,
): string {
  const key = slug.replace(/_/g, "");
  const authorStr = authors.length > 0 ? authors.join(" and ") : "Unknown";
  const lines = venue
    ? [
        `@article{${key},`,
        `  title={${title}},`,
        `  author={${authorStr}},`,
        year ? `  year={${year}},` : "",
        `  journal={${venue}},`,
        arxiv ? `  note={arXiv:${arxiv}},` : "",
        `}`,
      ]
    : [
        `@misc{${key},`,
        `  title={${title}},`,
        `  author={${authorStr}},`,
        year ? `  year={${year}},` : "",
        arxiv ? `  url={https://arxiv.org/abs/${arxiv}},` : "",
        `}`,
      ];
  return lines.filter(Boolean).join("\n") + "\n";
}

interface PaperContent {
  thesis?: string;
  problem?: string;
  method?: string;
  key_results?: string;
  assumptions?: string;
  limitations?: string;
  reusable?: string;
  open_questions?: string;
  project_relevance?: string;
}

const PAPER_MD_TEMPLATE = (title: string, content?: PaperContent) => {
  const c = content ?? {};
  return [
    `# ${title}`,
    "",
    "## One-line Thesis",
    "",
    c.thesis || "(single sentence capturing the paper's core contribution)",
    "",
    "## Problem / Gap",
    "",
    c.problem || "",
    "",
    "## Method",
    "",
    c.method || "",
    "",
    "## Key Results",
    "",
    c.key_results || "",
    "",
    "## Assumptions",
    "",
    c.assumptions || "",
    "",
    "## Limitations / Failure Modes",
    "",
    c.limitations || "",
    "",
    "## Reusable Ingredients",
    "",
    c.reusable || "(techniques, datasets, or insights that could be repurposed)",
    "",
    "## Open Questions",
    "",
    c.open_questions || "",
    "",
    "## Connections",
    "",
    "(auto-generated from edges.jsonl — do not edit manually)",
    "",
    "## Relevance to This Project",
    "",
    c.project_relevance || "",
    "",
  ].join("\n");
};

async function appendLog(action: string, summary: string, target?: string) {
  const entry: WikiLogEntry = {
    ts: new Date().toISOString(),
    action,
    target,
    summary,
  };
  await ResearchFS.appendJsonl(ResearchFS.resolve("literature/log.jsonl"), entry);
}

import { compareTitles, matchAuthorLists } from "../match";
import { cleanArxivId, resolveMetadata } from "../resolve";

// ── Action Handlers ────────────────────────────────────────────────────────

async function handleIngestPaper(params: any, activePhaseRun?: string, signal?: AbortSignal) {
  // Resolve metadata OUTSIDE the lock — external API calls are pure read
  // and holding the lock during them is the root cause of the deadlock.
  // The lock is only needed for the filesystem write portion below.
  if (!params.title && !params.arxiv && !params.doi) {
    return {
      title: "Missing identifier",
      output: "Provide at least one of: title, arxiv, or doi.",
      metadata: mdMeta({ error: "missing_identifier" }),
    };
  }

  const { resolved, warnings } = await resolveMetadata({
    title: params.title,
    authors: params.authors,
    year: params.year,
    venue: params.venue,
    arxiv: params.arxiv,
    doi: params.doi,
    signal,
  });

  const finalTitle = resolved.title ?? params.title ?? "Untitled";
  const finalAuthors = resolved.authors ?? params.authors ?? [];
  const finalYear = resolved.year ?? params.year;
  const finalVenue = resolved.venue ?? params.venue;
  const finalArxiv = resolved.arxiv ?? (params.arxiv ? cleanArxivId(params.arxiv) : undefined);
  const finalDoi = resolved.doi ?? params.doi;

  const firstAuthor = finalAuthors.at(0);
  const slug = params.slug_override || slugify(finalTitle, firstAuthor, finalYear);

  // Filesystem write portion — guarded by timeout-protected lock
  return withLockTimeout(wikiMutex, async () => {
    let finalSlug = slug;
    let suffix = 2;
    while (await ResearchFS.exists(ResearchFS.resolve("literature/papers", `${finalSlug}.yaml`))) {
      finalSlug = `${slug}_${suffix}`;
      suffix++;
    }
    const yamlPath = ResearchFS.resolve("literature/papers", `${finalSlug}.yaml`);
    const now = new Date().toISOString();

    const paper: LitPaperYaml = {
      slug: finalSlug,
      title: finalTitle,
      authors: finalAuthors,
      year: finalYear,
      venue: finalVenue,
      arxiv: finalArxiv,
      doi: finalDoi,
      tags: params.tags ?? [],
      relevance: params.relevance ?? "related",
      cite_key: finalSlug.replace(/_/g, ""),
      created: now,
      updated: now,
    };
    await ResearchFS.writeYaml(yamlPath, paper);

    try {
      const paperContent: PaperContent = {
        thesis: params.thesis,
        method: params.method,
        key_results: params.key_results,
        limitations: params.limitations,
        project_relevance: params.project_relevance,
      };
      const hasContent = Object.values(paperContent).some((v) => v);
      await ResearchFS.writeMd(
        ResearchFS.resolve("literature/papers", `${finalSlug}.md`),
        PAPER_MD_TEMPLATE(finalTitle, hasContent ? paperContent : undefined),
      );

      const bibLine = resolved.bibTeX
        ? resolved.bibTeX + "\n"
        : bibEntry(finalSlug, finalTitle, finalAuthors, finalYear, finalVenue, finalArxiv);
      await fs.appendFile(ResearchFS.resolve("literature/references.bib"), bibLine, "utf-8");

      await appendLog("ingest_paper", `Ingested paper: ${finalTitle} (source: ${resolved.source})`, finalSlug);
      await ResearchTimeline.append({
        type: "wiki.paper_ingested",
        id: finalSlug,
        title: finalTitle,
        summary: `Ingested paper: ${finalTitle}`,
      });

      // PhaseRun inner loop update (non-fatal)
      await updateActivePhaseRun(
        "ground",
        {
          incrementAttempts: true,
          summary: `Ingested paper: ${params.title ?? params.arxiv ?? "unknown"}`,
        },
        activePhaseRun,
      );

      const slugChanged = finalSlug !== slug;
      const outputLines = [
        `✅ Registered: ${finalSlug}`,
        `  Title: ${finalTitle}`,
        `  Authors: ${finalAuthors.join(", ") || "(unknown)"}`,
        `  Year: ${finalYear ?? "(unknown)"}`,
        `  Venue: ${finalVenue ?? "(unknown)"}`,
        `  Relevance: ${paper.relevance}`,
        `  BibTeX source: ${resolved.source}${resolved.source === "manual" ? " [UNVERIFIED]" : " ✓"}`,
        `  Content: ${hasContent ? "filled (thesis, method, results, etc.)" : "template only — edit .md to add details"}`,
        ...(slugChanged ? [`  ⚠️ Slug adjusted: ${slug} → ${finalSlug} (collision)`] : []),
      ];
      if (warnings.length > 0) {
        outputLines.push("", "Warnings:");
        for (const w of warnings) outputLines.push(`  ⚠️ ${w}`);
      }
      outputLines.push(
        "",
        `Files created:`,
        `  .research/literature/papers/${finalSlug}.yaml`,
        `  .research/literature/papers/${finalSlug}.md`,
        `  (bib entry appended to references.bib)`,
        "",
        `Next: Edit the .md file with paper details, then call research_wiki(action="link") to connect to related entities.`,
      );

      return {
        title: `Paper ingested: ${finalSlug}`,
        output: outputLines.join("\n"),
        metadata: mdMeta({ slug: finalSlug, source: resolved.source, warnings }),
      };
    } catch (err) {
      return {
        title: `Paper ingested (partial): ${finalSlug}`,
        output: [
          `⚠️ Created ${finalSlug}.yaml but some steps failed: ${err instanceof Error ? err.message : String(err)}`,
          `  Title: ${finalTitle}`,
          `  Files: .research/literature/papers/${finalSlug}.yaml`,
          `  The .md and/or bib entry may be missing — retry or create manually.`,
        ].join("\n"),
        metadata: mdMeta({ slug: finalSlug, source: resolved.source, partial: true }),
      };
    }
  });
}

async function handleLink(params: any, activePhaseRun?: string) {
  return withLockTimeout(wikiMutex, async () => {
    if (!params.from || !params.to || !params.edge_type) {
      return {
        title: "Missing edge parameters",
        output:
          'Provide from, to, and edge_type. Example: research_wiki(action="link", from="idea_003", to="chen2025_gap", edge_type="inspired_by")',
        metadata: mdMeta({ error: "missing_params" }),
      };
    }

    const [fromExists, toExists] = await Promise.all([entityExists(params.from), entityExists(params.to)]);
    if (!fromExists) {
      return {
        title: "Entity not found",
        output: `Source entity "${params.from}" does not exist.`,
        metadata: mdMeta({ error: "entity_not_found", entity: params.from }),
      };
    }
    if (!toExists) {
      return {
        title: "Entity not found",
        output: `Target entity "${params.to}" does not exist.`,
        metadata: mdMeta({ error: "entity_not_found", entity: params.to }),
      };
    }

    const edge: Edge = {
      from: params.from,
      to: params.to,
      type: params.edge_type,
      evidence: params.evidence,
      created: new Date().toISOString(),
    };
    await ResearchFS.appendJsonl(ResearchFS.resolve("literature/edges.jsonl"), edge);
    await appendLog("link", `${params.from} → ${params.to} [${params.edge_type}]`);
    await updateActivePhaseRun("ground", { summary: `Wiki updated: link` }, activePhaseRun);

    return {
      title: "Edge added",
      output: `✅ ${params.from} —[${params.edge_type}]→ ${params.to}${params.evidence ? ` (${params.evidence})` : ""}`,
      metadata: mdMeta({ from: params.from, to: params.to, type: params.edge_type }),
    };
  });
}

async function handleRegisterGap(params: any, activePhaseRun?: string) {
  return withLockTimeout(wikiMutex, async () => {
    if (!params.description) {
      return {
        title: "Missing description",
        output: "Please provide a gap description.",
        metadata: mdMeta({ error: "missing_description" }),
      };
    }

    const gapMapPath = ResearchFS.resolve("literature/gap_map.yaml");
    const existing = (await ResearchFS.readYaml<{ gaps: GapYaml[] }>(gapMapPath)) ?? { gaps: [] };
    const nextId = `G${String(existing.gaps.length + 1).padStart(2, "0")}`;

    const gap: GapYaml = {
      id: nextId,
      description: params.description,
      status: "open",
      source_paper: params.source_paper,
      linked_ideas: [],
      created: new Date().toISOString(),
    };
    existing.gaps.push(gap);
    await ResearchFS.writeYaml(gapMapPath, existing);
    await appendLog("register_gap", `Added gap ${nextId}: ${params.description}`, nextId);
    await ResearchTimeline.append({
      type: "wiki.gap_registered",
      id: nextId,
      summary: `Research gap registered: ${params.description?.slice(0, 80)}`,
    });

    await updateActivePhaseRun(
      "ground",
      {
        incrementAttempts: true,
        summary: `Registered gap ${nextId}: ${params.description?.slice(0, 60)}`,
      },
      activePhaseRun,
    );

    return {
      title: `Gap registered: ${nextId}`,
      output: [
        `✅ ${nextId}: ${params.description}`,
        `  Status: open`,
        ...(params.source_paper ? [`  Source: ${params.source_paper}`] : []),
        "",
        `Reference this gap as "${nextId}" in edges: research_wiki(action="link", from="idea_003", to="${nextId}", edge_type="addresses_gap")`,
      ].join("\n"),
      metadata: mdMeta({ id: nextId }),
    };
  });
}

async function handleUpdateEntry(params: any, activePhaseRun?: string) {
  return withLockTimeout(wikiMutex, async () => {
    if (!params.target_id || !params.field || !params.value) {
      return {
        title: "Missing update parameters",
        output:
          'Provide target_id, field, and value. Example: research_wiki(action="update_entry", target_id="chen2025_gap", field="relevance", value="core")',
        metadata: mdMeta({ error: "missing_params" }),
      };
    }

    // Update paper (target_id is a slug, not a gap ID)
    if (!params.target_id.startsWith("G")) {
      const yamlPath = ResearchFS.resolve("literature/papers", `${params.target_id}.yaml`);
      const paper = await ResearchFS.readYaml<LitPaperYaml>(yamlPath);
      if (!paper) {
        return {
          title: "Not found",
          output: `Paper "${params.target_id}" not found.`,
          metadata: mdMeta({ error: "not_found" }),
        };
      }

      if (params.field === "relevance" && PaperRelevance.safeParse(params.value).success) {
        paper.relevance = params.value as LitPaperYaml["relevance"];
      } else if (params.field === "tags") {
        const newTags = (params.value as string)
          .split(",")
          .map((t: string) => t.trim())
          .filter(Boolean);
        paper.tags = [...new Set([...(paper.tags ?? []), ...newTags])];
      } else {
        return {
          title: "Unknown field",
          output: `Cannot update field "${params.field}". Supported: relevance, tags.`,
          metadata: mdMeta({ error: "unknown_field" }),
        };
      }

      paper.updated = new Date().toISOString();
      await ResearchFS.writeYaml(yamlPath, paper);
      await appendLog(
        "update_entry",
        `Updated ${params.target_id}.${params.field} = ${params.value}`,
        params.target_id,
      );
      await updateActivePhaseRun("ground", { summary: `Wiki updated: update_entry` }, activePhaseRun);
      return {
        title: `${params.target_id} updated`,
        output: `✅ ${params.target_id}.${params.field} = ${params.value}`,
        metadata: mdMeta({ target_id: params.target_id, field: params.field, value: params.value }),
      };
    }

    // Update gap
    if (params.target_id.startsWith("G")) {
      const gapMapPath = ResearchFS.resolve("literature/gap_map.yaml");
      const data = (await ResearchFS.readYaml<{ gaps: GapYaml[] }>(gapMapPath)) ?? { gaps: [] };
      const gap = data.gaps.find((g) => g.id === params.target_id);
      if (!gap) {
        return {
          title: "Not found",
          output: `Gap "${params.target_id}" not found.`,
          metadata: mdMeta({ error: "not_found" }),
        };
      }

      if (params.field === "status" && GapStatus.safeParse(params.value).success) {
        gap.status = params.value as GapYaml["status"];
        if (params.value === "closed") gap.closed = new Date().toISOString();
      } else if (params.field === "linked_ideas") {
        const newIdeas = (params.value as string)
          .split(",")
          .map((s: string) => s.trim())
          .filter(Boolean);
        gap.linked_ideas = [...new Set([...(gap.linked_ideas ?? []), ...newIdeas])];
      } else {
        return {
          title: "Unknown field",
          output: `Cannot update gap field "${params.field}". Supported: status, linked_ideas.`,
          metadata: mdMeta({ error: "unknown_field" }),
        };
      }

      await ResearchFS.writeYaml(gapMapPath, data);
      await appendLog(
        "update_entry",
        `Updated gap ${params.target_id}.${params.field} = ${params.value}`,
        params.target_id,
      );
      await updateActivePhaseRun("ground", { summary: `Wiki updated: update_entry` }, activePhaseRun);

      return {
        title: `Gap ${params.target_id} updated`,
        output: `✅ ${params.target_id}.${params.field} = ${params.value}`,
        metadata: mdMeta({ target_id: params.target_id, field: params.field, value: params.value }),
      };
    }

    return {
      title: "Unknown target",
      output: `Cannot determine if "${params.target_id}" is a paper or gap.`,
      metadata: mdMeta({ error: "unknown_target" }),
    };
  });
}

async function handleQuery(params: any) {
  const papers: LitPaperYaml[] = [];
  const kpDir = ResearchFS.resolve("literature/papers");
  const yamlFiles = await ResearchFS.listYaml(kpDir);
  for (const file of yamlFiles) {
    const p = await ResearchFS.readYaml<LitPaperYaml>(ResearchFS.resolve("literature/papers", file));
    if (p) papers.push(p);
  }

  const gapData = (await ResearchFS.readYaml<{ gaps: GapYaml[] }>(ResearchFS.resolve("literature/gap_map.yaml"))) ?? {
    gaps: [],
  };
  const edges = await ResearchFS.readJsonl<Edge>(ResearchFS.resolve("literature/edges.jsonl"));

  // Read state for project name
  const state = await ResearchFS.readYaml<StateYaml>(ResearchFS.resolve("state.yaml"));
  const projectName = state?.project ?? "Research";

  // Build LIT_CONTEXT.md
  const sortedPapers = [...papers].sort((a, b) => {
    const relOrder = { core: 0, related: 1, peripheral: 2 };
    return (relOrder[a.relevance] ?? 2) - (relOrder[b.relevance] ?? 2);
  });

  const openGaps = gapData.gaps.filter((g) => g.status === "open");
  const failedIdeas = edges.filter((e) => e.type === "invalidates");

  const lines: string[] = [
    `# Literature Context: ${projectName}`,
    "",
    "## Key Papers",
    "| Slug | One-line Thesis | Relevance | Tags |",
    "|------|----------------|-----------|------|",
  ];

  for (const p of sortedPapers.slice(0, 15)) {
    lines.push(`| ${p.slug} | (see ${p.slug}.md) | ${p.relevance} | ${p.tags.join(", ")} |`);
  }

  lines.push("", "## Active Gaps");
  for (const g of openGaps) {
    lines.push(`${g.id}. ${g.description}${g.source_paper ? ` — source: ${g.source_paper}` : ""}`);
  }

  if (failedIdeas.length > 0) {
    lines.push("", "## Failed Approaches (banlist)");
    for (const e of failedIdeas) {
      lines.push(`- ${e.from} → invalidated by ${e.to}${e.evidence ? `: ${e.evidence}` : ""}`);
    }
  }

  lines.push("", "## Known Baselines", "(populate from papers/*.md Key Results sections)");

  lines.push("", "## Open Questions", "(populate from papers/*.md Open Questions sections)");

  lines.push("", "## Time-Critical Signals", "(papers and findings from last 3 months — check dates)");

  // Active chains
  const chains: string[] = [];
  for (const gap of openGaps.slice(0, 3)) {
    const addressing = edges.filter((e) => e.to === gap.id && e.type === "addresses_gap");
    const ideaRefs = addressing.map((e) => e.from).filter((f) => f.startsWith("idea_"));
    if (ideaRefs.length > 0) {
      chains.push(`${gap.description} ← ${ideaRefs.join(", ")}`);
    } else {
      chains.push(`${gap.description} ← (no idea yet)`);
    }
  }
  if (chains.length > 0) {
    lines.push("", "## Active Chains", ...chains);
  }

  const content = lines.join("\n");
  await ResearchFS.writeMd(ResearchFS.resolve("literature/LIT_CONTEXT.md"), content);
  await appendLog("query", "Regenerated LIT_CONTEXT.md");

  return {
    title: "LIT_CONTEXT.md generated",
    output: [
      `✅ Compressed view generated (${content.length} chars)`,
      `  Papers: ${papers.length} (${papers.filter((p) => p.relevance === "core").length} core)`,
      `  Gaps: ${gapData.gaps.length} (${openGaps.length} open)`,
      `  Edges: ${edges.length}`,
      `  Failed approaches in banlist: ${failedIdeas.length}`,
      "",
      `File: .research/literature/LIT_CONTEXT.md`,
    ].join("\n"),
    metadata: mdMeta({ papers: papers.length, gaps: gapData.gaps.length, edges: edges.length, chars: content.length }),
  };
}

async function handleLint(params: any) {
  const issues: string[] = [];

  const kpDir = ResearchFS.resolve("literature/papers");
  const yamlFiles = await ResearchFS.listYaml(kpDir);
  const papers: LitPaperYaml[] = [];
  const slugs = new Set<string>();

  for (const file of yamlFiles) {
    const p = await ResearchFS.readYaml<LitPaperYaml>(ResearchFS.resolve("literature/papers", file));
    if (p) {
      papers.push(p);
      slugs.add(p.slug);
    }
  }

  const edges = await ResearchFS.readJsonl<Edge>(ResearchFS.resolve("literature/edges.jsonl"));
  const gapData = (await ResearchFS.readYaml<{ gaps: GapYaml[] }>(ResearchFS.resolve("literature/gap_map.yaml"))) ?? {
    gaps: [],
  };
  const gapIds = new Set(gapData.gaps.map((g) => g.id));

  // Orphan papers (no edges)
  const papersWithEdges = new Set(edges.flatMap((e) => [e.from, e.to]).filter((id) => slugs.has(id)));
  for (const p of papers) {
    if (!papersWithEdges.has(p.slug)) {
      issues.push(`ORPHAN: paper ${p.slug} has no edges`);
    }
  }

  // Sparse pages (md file missing key sections)
  for (const p of papers) {
    const md = await ResearchFS.readMd(ResearchFS.resolve("literature/papers", `${p.slug}.md`));
    if (md) {
      const emptySections = ["## Method", "## Key Results", "## Relevance to This Project"].filter((section) => {
        const idx = md.indexOf(section);
        if (idx === -1) return true;
        const nextSection = md.indexOf("##", idx + section.length);
        const content = md.slice(idx + section.length, nextSection === -1 ? undefined : nextSection).trim();
        return content.length < 5;
      });
      if (emptySections.length >= 2) {
        issues.push(`SPARSE: ${p.slug} has ${emptySections.length} empty key sections: ${emptySections.join(", ")}`);
      }
    }
  }

  // Stale gaps (open for >30 days with no linked ideas)
  const now = Date.now();
  for (const g of gapData.gaps) {
    if (g.status === "open" && g.linked_ideas.length === 0) {
      const age = now - new Date(g.created).getTime();
      if (age > 30 * 24 * 60 * 60 * 1000) {
        issues.push(`STALE_GAP: ${g.id} open for >30 days with no linked ideas`);
      }
    }
  }

  // Dangling edges (reference non-existent entity)
  const ideaSlugs = new Set(
    (await ResearchFS.listYaml(ResearchFS.resolve("ideas"))).map((f) => f.replace(".yaml", "")),
  );
  const _allKnownIds = new Set([...slugs, ...gapIds, ...ideaSlugs]);
  for (const e of edges) {
    if (!slugs.has(e.from) && !gapIds.has(e.from) && !ideaSlugs.has(e.from)) {
      issues.push(`DANGLING: edge from "${e.from}" — entity not found in wiki/ideas`);
    }
    if (!slugs.has(e.to) && !gapIds.has(e.to) && !ideaSlugs.has(e.to)) {
      issues.push(`DANGLING: edge to "${e.to}" — entity not found in wiki/ideas/gaps`);
    }
  }

  // Duplicate bib entries
  const bib = await ResearchFS.readMd(ResearchFS.resolve("literature/references.bib"));
  if (bib) {
    const keys = [...bib.matchAll(/@\w+\{(\w+)/g)].map((m) => m[1]!);
    const seen = new Set<string>();
    for (const key of keys) {
      if (seen.has(key)) issues.push(`DUP_BIB: duplicate citation key "${key}"`);
      seen.add(key);
    }
  }

  if (issues.length === 0) {
    return {
      title: "Wiki health check",
      output: "✅ No issues found.",
      metadata: mdMeta({ issues: 0 }),
    };
  }

  return {
    title: `Wiki health check: ${issues.length} issues`,
    output: issues.map((i) => `- ${i}`).join("\n"),
    metadata: mdMeta({ issues: issues.length }),
  };
}

async function handleVerifyBib(params: any) {
  const kpDir = ResearchFS.resolve("literature/papers");
  const yamlFiles = await ResearchFS.listYaml(kpDir);
  const papers: LitPaperYaml[] = [];
  for (const file of yamlFiles) {
    const p = await ResearchFS.readYaml<LitPaperYaml>(ResearchFS.resolve("literature/papers", file));
    if (p) papers.push(p);
  }

  const results: { slug: string; status: string; details: string }[] = [];
  let verified = 0;
  let mismatch = 0;
  let unverifiable = 0;

  for (const paper of papers) {
    if (!paper.arxiv && !paper.doi) {
      results.push({
        slug: paper.slug,
        status: "UNVERIFIABLE",
        details: "No arxiv or doi — cannot verify against authoritative source",
      });
      unverifiable++;
      continue;
    }

    const { resolved, warnings: verifyWarnings } = await resolveMetadata({
      title: paper.title,
      arxiv: paper.arxiv ? cleanArxivId(paper.arxiv) : undefined,
      doi: paper.doi,
    });

    if (resolved.source === "manual") {
      const cause = verifyWarnings.length > 0 ? verifyWarnings[verifyWarnings.length - 1]! : "API lookup failed";
      results.push({ slug: paper.slug, status: "UNVERIFIABLE", details: cause });
      unverifiable++;
      continue;
    }

    const issues: string[] = [];

    // Title comparison (robust: normalization + fuzzy token matching)
    if (resolved.title && paper.title) {
      const titleResult = compareTitles(paper.title, resolved.title);
      if (titleResult.level === "mismatch") {
        issues.push(
          `title mismatch: local="${paper.title}" vs source="${resolved.title}" (score=${titleResult.score.toFixed(2)})`,
        );
      } else if (titleResult.level === "fuzzy_match") {
        issues.push(
          `title fuzzy match: local="${paper.title}" ≈ source="${resolved.title}" (score=${titleResult.score.toFixed(2)})`,
        );
      }
    }

    if (resolved.year && paper.year && resolved.year !== paper.year) {
      issues.push(`year mismatch: local=${paper.year} vs source=${resolved.year}`);
    }

    // Author comparison (full-list matching with Hungarian algorithm)
    if (resolved.authors && resolved.authors.length > 0 && paper.authors.length > 0) {
      const authorResult = matchAuthorLists(paper.authors, resolved.authors);
      for (const c of authorResult.conflicts) {
        if (c.severity === "error") {
          issues.push(`author ${c.type}: ${c.description}`);
        }
      }
      if (authorResult.score < 0.5) {
        issues.push(
          `author list low match score: ${authorResult.score.toFixed(2)} (${authorResult.pairs.length}/${Math.max(paper.authors.length, resolved.authors.length)} matched)`,
        );
      }
    }

    if (issues.length === 0) {
      results.push({ slug: paper.slug, status: "VERIFIED", details: `Confirmed via ${resolved.source}` });
      verified++;
    } else {
      results.push({ slug: paper.slug, status: "MISMATCH", details: issues.join("; ") });
      mismatch++;
    }
  }

  const summary = [
    `=== BibTeX Verification Report ===`,
    "",
    `Total entries: ${papers.length}`,
    `  ✅ Verified: ${verified}`,
    `  ❌ Mismatch: ${mismatch}`,
    `  ❓ Unverifiable: ${unverifiable}`,
  ];

  if (mismatch > 0) {
    summary.push("", "Mismatches:");
    for (const r of results.filter((r) => r.status === "MISMATCH")) {
      summary.push(`  ${r.slug}: ${r.details}`);
    }
  }

  if (unverifiable > 0) {
    summary.push("", "Unverifiable (no arxiv/doi):");
    for (const r of results.filter((r) => r.status === "UNVERIFIABLE")) {
      summary.push(`  ${r.slug}: ${r.details}`);
    }
  }

  await appendLog(
    "verify_bib",
    `Verified ${papers.length} entries: ${verified} ok, ${mismatch} mismatch, ${unverifiable} unverifiable`,
  );

  return {
    title: `BibTeX verification: ${verified}✅ ${mismatch}❌ ${unverifiable}❓`,
    output: summary.join("\n"),
    metadata: mdMeta({ total: papers.length, verified, mismatch, unverifiable, results }),
  };
}

async function handleStats(params: any) {
  const kpDir = ResearchFS.resolve("literature/papers");
  const yamlFiles = await ResearchFS.listYaml(kpDir);
  const papers: LitPaperYaml[] = [];
  for (const file of yamlFiles) {
    const p = await ResearchFS.readYaml<LitPaperYaml>(ResearchFS.resolve("literature/papers", file));
    if (p) papers.push(p);
  }

  const edges = await ResearchFS.readJsonl<Edge>(ResearchFS.resolve("literature/edges.jsonl"));
  const gapData = (await ResearchFS.readYaml<{ gaps: GapYaml[] }>(ResearchFS.resolve("literature/gap_map.yaml"))) ?? {
    gaps: [],
  };
  const log = await ResearchFS.readJsonl<WikiLogEntry>(ResearchFS.resolve("literature/log.jsonl"));

  const coreCount = papers.filter((p) => p.relevance === "core").length;
  const relatedCount = papers.filter((p) => p.relevance === "related").length;
  const periphCount = papers.filter((p) => p.relevance === "peripheral").length;
  const openGaps = gapData.gaps.filter((g) => g.status === "open").length;
  const closedGaps = gapData.gaps.filter((g) => g.status === "closed").length;

  const edgeTypeCounts: Record<string, number> = {};
  for (const e of edges) {
    edgeTypeCounts[e.type] = (edgeTypeCounts[e.type] ?? 0) + 1;
  }

  const lines = [
    "=== Literature Wiki Stats ===",
    "",
    `Papers: ${papers.length} (${coreCount} core, ${relatedCount} related, ${periphCount} peripheral)`,
    `Gaps: ${gapData.gaps.length} (${openGaps} open, ${closedGaps} closed)`,
    `Edges: ${edges.length}`,
    `Log entries: ${log.length}`,
  ];

  if (Object.keys(edgeTypeCounts).length > 0) {
    lines.push("", "Edge types:");
    for (const [type, count] of Object.entries(edgeTypeCounts).sort((a, b) => b[1] - a[1])) {
      lines.push(`  ${type}: ${count}`);
    }
  }

  if (log.length > 0) {
    const lastLog = log[log.length - 1];
    lines.push("", `Last mutation: ${lastLog?.ts}`);
  }

  return {
    title: "Literature Wiki Stats",
    output: lines.join("\n"),
    metadata: mdMeta({ papers: papers.length, gaps: gapData.gaps.length, edges: edges.length, log: log.length }),
  };
}

// ── Tool Definition ────────────────────────────────────────────────────────

export const researchWiki = tool({
  description: DESCRIPTION,
  args: {
    action: z
      .enum(["ingest_paper", "link", "register_gap", "update_entry", "query", "lint", "verify_bib", "stats"])
      .describe("Operation to perform"),

    title: z.string().optional().describe("Paper title. Required for ingest_paper."),
    authors: z.array(z.string()).optional().describe("Author list. For ingest_paper."),
    year: z.number().optional().describe("Publication year. For ingest_paper."),
    venue: z.string().optional().describe("Venue (e.g. 'ICML 2026', 'arXiv'). For ingest_paper."),
    arxiv: z.string().optional().describe("arXiv ID (e.g. '2501.12345'). For ingest_paper."),
    doi: z.string().optional().describe("DOI. For ingest_paper."),
    tags: z.array(z.string()).optional().describe("Topic tags. For ingest_paper or update_entry."),
    relevance: PaperRelevance.optional().describe(
      "Relevance: core, related, peripheral. For ingest_paper or update_entry.",
    ),
    slug_override: z.string().optional().describe("Override auto-generated slug. For ingest_paper."),

    thesis: z.string().optional().describe("One-line thesis of the paper. For ingest_paper — fills the md template."),
    method: z.string().optional().describe("Method summary. For ingest_paper — fills the md template."),
    key_results: z.string().optional().describe("Key results with numbers. For ingest_paper — fills the md template."),
    limitations: z
      .string()
      .optional()
      .describe("Limitations and failure modes. For ingest_paper — fills the md template."),
    project_relevance: z
      .string()
      .optional()
      .describe("Why this paper matters for our project. For ingest_paper — fills the md template."),

    from: z.string().optional().describe("Source entity. For link."),
    to: z.string().optional().describe("Target entity. For link."),
    edge_type: EdgeType.optional().describe("Relationship type. For link."),
    evidence: z.string().optional().describe("Why this relationship exists. For link."),

    description: z.string().optional().describe("Gap description. Required for register_gap."),
    source_paper: z.string().optional().describe("Paper slug that reveals this gap. For register_gap."),

    target_id: z.string().optional().describe("Paper slug or gap ID to update. For update_entry."),
    field: z.string().optional().describe("Field to update. For update_entry."),
    value: z.string().optional().describe("New value. For update_entry."),

    // query
    force: z.boolean().optional().describe("Force regenerate LIT_CONTEXT.md even if not stale. For query."),
  },
  async execute(params, ctx) {
    return withGuard(async () => {
      if (!(await ResearchFS.isInitialized())) return notInitialized();
      const state = await ResearchFS.readYaml<StateYaml>(ResearchFS.resolve("state.yaml"));
      const activePhaseRun = state?.focus?.active_phase_run;
      const signal = ctx?.abort;
      switch (params.action) {
        case "ingest_paper":
          return handleIngestPaper(params, activePhaseRun, signal);
        case "link":
          return handleLink(params, activePhaseRun);
        case "register_gap":
          return handleRegisterGap(params, activePhaseRun);
        case "update_entry":
          return handleUpdateEntry(params, activePhaseRun);
        case "query":
          return handleQuery(params);
        case "lint":
          return handleLint(params);
        case "verify_bib":
          return handleVerifyBib(params);
        case "stats":
          return handleStats(params);
        default:
          return {
            title: "Unknown action",
            output: `Unknown action: ${params.action}`,
            metadata: mdMeta({ error: "unknown_action" }),
          };
      }
    });
  },
});
